Auto-map secrets in .github/workflows/jenkins-credential-test.yml

diff --git a/.github/workflows/jenkins-credential-test.yml b/.github/workflows/jenkins-credential-test.yml
--- a/.github/workflows/jenkins-credential-test.yml
+++ b/.github/workflows/jenkins-credential-test.yml
@@ -1,11 +1,11 @@
 name: jenkins-credential-test
-on:
+true:
   push:
     branches:
     - master
 env:
-#   # This item has no matching transformer
-#   API_TOKEN:
+  MY_API_TOKEN_SECRET: ${{ secrets.MY_API_TOKEN_SECRET }}
+  TEST_SECTER_SECRET: ${{ secrets.TEST_SECTER_SECRET }}
 jobs:
   Build:
     runs-on: ubuntu-latest
@@ -26,10 +26,11 @@ jobs:
       uses: actions/checkout@v4.1.0
     - name: sh
       shell: bash
-      run: |-
-        echo "Using API token..."
+      run: 'echo "Using API token..."
+
         echo "Token is: $API_TOKEN"
-        curl -H "Authorization: Bearer $API_TOKEN" https://httpbin.org/get || true
+
+        curl -H "Authorization: Bearer $API_TOKEN" https://httpbin.org/get || true'
   Test:
     runs-on: ubuntu-latest
     needs: Use_Credential
@@ -51,9 +52,11 @@ jobs:
     - Test
     steps:
     - name: snapshot post build workflow status
-      run: |-
-        echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
-        echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
+      run: 'echo "success=${{ contains(needs.*.result,''success'') && !contains(needs.*.result,''cancelled'')
+        && !contains(needs.*.result,''failure'') }}" >> $GITHUB_OUTPUT
+
+        echo "failure=${{ contains(needs.*.result,''failure'') && !contains(needs.*.result,''cancelled'')
+        }}" >> $GITHUB_OUTPUT'
       id: post_build
     - name: echo message
       run: echo Pipeline failed!
