Auto-map secrets in .github/workflows/jenkins-credential-test.yml

diff --git a/.github/workflows/jenkins-credential-test.yml b/.github/workflows/jenkins-credential-test.yml
--- a/.github/workflows/jenkins-credential-test.yml
+++ b/.github/workflows/jenkins-credential-test.yml
@@ -1,10 +1,9 @@
 name: jenkins-credential-test
-on:
+true:
   push:
     branches:
     - master
 env:
-#   # This item has no matching transformer
   API_TOKEN: ${{ secrets.MY_API_TOKEN_SECRET }}
 jobs:
   Build:
@@ -17,6 +16,9 @@ jobs:
     - name: sh
       shell: bash
       run: echo build complete
+    env:
+      MY_API_TOKEN_SECRET: ${{ secrets.MY_API_TOKEN_SECRET }}
+      TEST_SECTER_SECRET: ${{ secrets.TEST_SECTER_SECRET }}
   Use_Credential:
     name: Use Credential
     runs-on: ubuntu-latest
@@ -26,10 +28,14 @@ jobs:
       uses: actions/checkout@v4.1.0
     - name: sh
       shell: bash
-      run: |-
-        echo "Using API token..."
+      run: 'echo "Using API token..."
+
         echo "Token is: $API_TOKEN"
-        curl -H "Authorization: Bearer $API_TOKEN" https://httpbin.org/get || true
+
+        curl -H "Authorization: Bearer $API_TOKEN" https://httpbin.org/get || true'
+    env:
+      MY_API_TOKEN_SECRET: ${{ secrets.MY_API_TOKEN_SECRET }}
+      TEST_SECTER_SECRET: ${{ secrets.TEST_SECTER_SECRET }}
   Test:
     runs-on: ubuntu-latest
     needs: Use_Credential
@@ -41,6 +47,9 @@ jobs:
     - name: sh
       shell: bash
       run: echo all tests passed
+    env:
+      MY_API_TOKEN_SECRET: ${{ secrets.MY_API_TOKEN_SECRET }}
+      TEST_SECTER_SECRET: ${{ secrets.TEST_SECTER_SECRET }}
   Post-Build:
     if: always()
     name: Post Build
@@ -51,9 +60,11 @@ jobs:
     - Test
     steps:
     - name: snapshot post build workflow status
-      run: |-
-        echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
-        echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
+      run: 'echo "success=${{ contains(needs.*.result,''success'') && !contains(needs.*.result,''cancelled'')
+        && !contains(needs.*.result,''failure'') }}" >> $GITHUB_OUTPUT
+
+        echo "failure=${{ contains(needs.*.result,''failure'') && !contains(needs.*.result,''cancelled'')
+        }}" >> $GITHUB_OUTPUT'
       id: post_build
     - name: echo message
       run: echo Pipeline failed!
@@ -61,3 +72,6 @@ jobs:
     - name: echo message
       run: echo Pipeline succeeded!
       if: steps.post_build.outputs.success == 'true'
+    env:
+      MY_API_TOKEN_SECRET: ${{ secrets.MY_API_TOKEN_SECRET }}
+      TEST_SECTER_SECRET: ${{ secrets.TEST_SECTER_SECRET }}
